### ISSUE TITLE
File watch not working

### ISSUE THREAD

**Issue by vizo** [catberry/catberry-l10n#18]
When i change l10n json files, they are not reloaded. I checked source and on('change') event never fires. I need to manually restart server every time ...

Any idea?

Thanks.

**Comment by pragmadash** [comment]
Could you share more details about your environment?
OS, filesystem, are you using a container or remote resource for publishing changes, etc.

**Comment by pragmadash** [comment]
Checked on OS X, works for me.
How can I reproduce the issue? Could you describe some steps?

**Comment by vizo** [comment]
I am using Ubuntu 15.10.
node --version
v5.10.1

**Comment by pragmadash** [comment]
@vizo wait, if you mean `l10n` directory in your project's root it's not watched on purpose. The `l10n` directories inside components are watched. The root `l10n` directory is for global values which are rarely changed.

**Comment by vizo** [comment]
Ok, clear. Why we can't watch both?

**Comment by pragmadash** [comment]
Global l10n directory is kinda a backup option. I would put such kind of files to a `document` component then. But the best practice is to separate the files by components having isolated components published to a shared repo across several teams.

**Comment by vizo** [comment]
Ok thanks for explanation.
